#!/usr/bin/env bash

cd "$(dirname "$0")"
SCRIPT_DIR="$(pwd)"

HOME_CONFIG_DIR=$HOME/.config

ALACRITTY_CONFIG_DEST_DIR=$HOME_CONFIG_DIR/alacritty
LVIM_CONFIG_DEST_DIR=$HOME_CONFIG_DIR/lvim
PAYPAL_CONFIG_DEST_DIR=$HOME_CONFIG_DIR/paypal

ZSHRC_DEST_PATH=$HOME/.zshrc
TMUX_CONF_DEST_PATH=$HOME/.tmux.conf
TMUX_CONF_LOCAL_DEST_PATH=$HOME/.tmux.conf.local
GITHUB_CONFIG_DEST_PATH=$HOME/.gitconfig
ALACRITTY_DEST_PATH=$ALACRITTY_CONFIG_DEST_DIR/alacritty.yml
