#!/usr/bin/env bash
# Regenerates the dotfiles-managed block in ~/.ssh/config from ssh-machines.
# Replaces the block in place if it exists (preserving any surrounding config
# the user added by hand), or appends it if this is the first run.
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MACHINES_FILE="$DOTFILES_DIR/ssh-machines"
SSH_DIR="${HOME}/.ssh"
SSH_CONFIG="${SSH_DIR}/config"
BEGIN_MARK="# BEGIN dotfiles-managed-hosts"
END_MARK="# END dotfiles-managed-hosts"

mkdir -p "$SSH_DIR"
touch "$SSH_CONFIG"

newblock="$(mktemp)"
trap 'rm -f "$newblock"' EXIT

{
	echo "$BEGIN_MARK"
	echo "# Generated by 'make ssh-config' from ssh-machines -- do not edit by hand"
	while read -r name conn; do
		case "$name" in ""|"#"*) continue ;; esac
		user="${conn%%@*}"
		host="${conn##*@}"
		echo ""
		echo "Host $name"
		echo "    HostName $host"
		echo "    User $user"
	done < "$MACHINES_FILE"
	echo "$END_MARK"
} > "$newblock"

tmp="$(mktemp)"
if grep -qF "$BEGIN_MARK" "$SSH_CONFIG"; then
	awk -v newblock="$newblock" -v begin="$BEGIN_MARK" -v end="$END_MARK" '
		$0 == begin {
			while ((getline line < newblock) > 0) print line
			skip = 1
			next
		}
		$0 == end { skip = 0; next }
		skip { next }
		{ print }
	' "$SSH_CONFIG" > "$tmp"
else
	cp "$SSH_CONFIG" "$tmp"
	echo "" >> "$tmp"
	cat "$newblock" >> "$tmp"
fi

mv "$tmp" "$SSH_CONFIG"
chmod 600 "$SSH_CONFIG"

hosts="$(awk '!/^#/ && NF {printf "%s ", $1}' "$MACHINES_FILE")"
echo "ssh config updated: $hosts"
