[ui]
# Show account name in sidebar
sidebar-width=28
# Time format
timestamp-format=2006-01-02 15:04
this-day-time-format=15:04
this-year-time-format=Jan 02 15:04

[viewer]
pager=less -R
alternatives=text/plain,text/html

[compose]
editor=nvim

[filters]
text/html=pandoc -f html -t plain
text/plain=colorize
